export enum Routes {
  Discover = '/',
  Songs = '/songs',
  Albums = '/albums',
  Artists = '/artists',
  Genres = '/genres',
  RecentlyPlayed = '/recently-played',
  FavoriteSongs = '/favorite-songs',
  Search = '/search',
  Admin = '/admin',
  AdminSongs = '/admin/songs',
  AdminArtists = '/admin/artists',
  AdminAlbums = '/admin/albums',
  AdminGenres = '/admin/genres',
}
